// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9G1F3ZeNL6bec2TOWUnfgtQJZc1eWoSs',
    appId: '1:40325321577:web:381aea993b8bc68c9963f8',
    messagingSenderId: '40325321577',
    projectId: 'todo-c8-369d4',
    authDomain: 'todo-c8-369d4.firebaseapp.com',
    storageBucket: 'todo-c8-369d4.appspot.com',
    measurementId: 'G-VT2LR678KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwDFXPlrbbh3tebMopzDteJVR9UK6ze3A',
    appId: '1:40325321577:android:f554d21cee2c716b9963f8',
    messagingSenderId: '40325321577',
    projectId: 'todo-c8-369d4',
    storageBucket: 'todo-c8-369d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx09kXre2GvpM6aSvhWRIyG1vbVpoxjXQ',
    appId: '1:40325321577:ios:884870f76dfddaa29963f8',
    messagingSenderId: '40325321577',
    projectId: 'todo-c8-369d4',
    storageBucket: 'todo-c8-369d4.appspot.com',
    iosClientId: '40325321577-7ridhjd17bhod67mvi8jp2erafn9cjqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx09kXre2GvpM6aSvhWRIyG1vbVpoxjXQ',
    appId: '1:40325321577:ios:9749a2ad4ca5b00b9963f8',
    messagingSenderId: '40325321577',
    projectId: 'todo-c8-369d4',
    storageBucket: 'todo-c8-369d4.appspot.com',
    iosClientId: '40325321577-lj1h2a34ngvuln994oj6gd2n9r8ri3ls.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
